version: '3'
services:
  hardhat-node:
    build: .
    command: npx hardhat node
    ports:
      - "8545:8545"
  
  scripts:
    build: .
    env_file: .env
    depends_on:
      - hardhat-node
    volumes:
      - ./data:/app/data